kathmandu777/i-make

.pre-commit-config.yaml
README.md

Usageの手順を明確化
markdownlint, markdownlint-fix のpre-commit
Close #
1.

docs: setup procedure

---

.gitignore
.pre-commit-config.yaml
gen2-facemesh/main_depthai_camera.py
i-make/__main__.py
i-make/libs/effect.py

Close #19
おまかせします
- メイクのみ投影できるかどうか
- docstringがしっかりと記述できているかどうか

Projector irradiation

---

i-make/__main__.py
i-make/libs/diagnosis.py

目のサイズより目の間の距離が長いかどうかを診断するクラスの作成
Close #32 
1. `python -m i-make`
- 変数名
- 関数の分け方
- クラスの作成の仕方

feat: eye distance

---

i-make/__main__.py
i-make/libs/effect.py
i-make/libs/makeup.py

メイク素材を重ね合わせて投影するクラスの作成
Close #33 
1.

feat: makeup class

---

i-make/__main__.py
i-make/mode/base.py

Reverts kathmandu777/i-make#50

Revert "色変更機能追加"

---

i-make/vue/src/components/Choice.vue

チェックボックスを選択すると即時で Video に反映されるように
Close #
1. 
チェックボックスを選択したり、外したりをしていると著しくFPSが落ちる。これはボタンでも再現できる

dynamic changing selected image

---

poetry.lock

chore: update versions

---

i-make/mode/custom.py

feat: can show custom thumbnails

---

i-make/mode/diagnosis.py
i-make/static/facepaints/diagnosis/data.jsonc

fix: diagnosis color bug

---

i-make/vue/src/components/mode/custom/Custom.vue
i-make/vue/src/components/shared/Choices.vue
i-make/vue/src/components/shared/SingleEffect.vue
i-make/vue/src/components/shared/SkinColor.vue
i-make/vue/src/views/TwoColumn.vue

design: bg color to black

---

.pre-commit-config.yaml
.prettierrc
i-make/vue/src/App.vue
i-make/vue/src/components/mode/Diagnosis.vue
i-make/vue/src/components/mode/Easy.vue
i-make/vue/src/components/mode/Event.vue
i-make/vue/src/components/mode/Practice.vue
i-make/vue/src/components/mode/custom/Custom.vue
i-make/vue/src/components/mode/custom/CustomChoices.vue
i-make/vue/src/components/shared/Choices.vue
i-make/vue/src/components/shared/Menu.vue
i-make/vue/src/components/shared/SingleEffect.vue
i-make/vue/src/components/shared/SkinColor.vue
i-make/vue/src/components/shared/Video.vue
i-make/vue/src/views/TwoColumn.vue

Linter for vue

---

i-make/__main__.py
i-make/libs/diagnosis.py

feat: 目の距離の診断時に顔を投影しないようにした

---

i-make/__main__.py
i-make/mode/diagnosis.py
i-make/vue/src/components/mode/Diagnosis.vue

feat: show diagnosis results

---

imake/vue/src/components/mode/Diagnosis.vue

design: diagnosis button color

---

imake/vue/src/components/mode/custom/Custom.vue

diagnosisのアイコン追加は保留とする
Close #87 
1.

design: add icon of custom

---

imake/__main__.py
imake/libs/diagnosis.py

feat: eye_size_ratio #123

---

imake/vue/src/components/mode/custom/Custom.vue
imake/vue/src/components/mode/custom/CustomChoices.vue
imake/vue/src/components/templates/Choices.vue

https://user-images.githubusercontent.com/57817950/194791860-c98ae1f1-80c4-4ed3-9c7a-4ed6b2217839.mov
Close #79 
1. 
画面遷移までの秒数が適切か？ (150ms)

feat: can know which button was pressed

---

imake/__main__.py
imake/dataclasses/diagnosis.py
imake/mode/diagnosis.py
imake/static/modes/diagnosis/data.yml
imake/vue/src/components/mode/Diagnosis.vue

feat: improve diagnosis result ui

---

imake/__main__.py
imake/vue/src/components/mode/Diagnosis.vue
imake/vue/src/components/mode/custom/Custom.vue
imake/vue/src/components/templates/SingleEffect.vue

refactor: __main__.py

---

imake/static/modes/diagnosis/data.yml

fix: base color answer_id reverse

---

imake/static/modes/diagnosis/data.yml
imake/vue/src/components/mode/Diagnosis.vue

fix: Diagnosis.vue bug and data.yml

---

imake/__main__.py
imake/libs/face_detection.py
imake/mode/__init__.py
imake/mode/config.py
imake/vue/src/components/modules/Config.vue
imake/vue/src/components/modules/Menu.vue
imake/vue/src/views/TwoColumn.vue

Close #126 
Close #127 
Close #142 
1.

feat: config mode (offset, scale) #126

---

imake/__main__.py
imake/libs/diagnosis.py

fix: 目の距離の描画ができるように

---

imake/mode/base.py

fix: 目の周りの赤色の点が出ないように

---

imake/__main__.py

feat: margin height width

---

imake/mode/base.py
imake/mode/custom.py

fix: practice order

---

imake/libs/palette.py
imake/vue/src/components/mode/custom/CustomChoices.vue
imake/vue/src/components/modules/SkinColor.vue

fix: hsvToRgbCode
